version: '3.8'

services:
  redrob-ranker:
    build:
      context: .
      dockerfile: Dockerfile
    image: manojc13/redrob-ranker:latest
    container_name: redrob_candidate_ranking
    volumes:
      - ./data:/app/data
      - ./OUTPUT:/app/OUTPUT
    command: ["--candidates", "/app/data/candidates.jsonl", "--out", "/app/OUTPUT/submission.csv"]
    environment:
      - PYTHONUNBUFFERED=1
    mem_limit: 16g
    cpus: 4
